### ISSUE TITLE
Revert aave-v2 supply/borrow paused guards

### ISSUE THREAD

**Issue by Rubilmax** [morpho-dao/morpho-v1#1628]

**Comment by MerlinEgalite** [comment]
@pakim249CAL to link to the PR

**Comment by MathisGD** [comment]
Can someone provide a quick description of why we are going back please ? I was not able to follow the discussion yesterday.

**Comment by pakim249CAL** [comment]
A few reasons given:

1. No amount of checks will be sufficient, and we should be proactive about pausing before the underlying pool does.
2. Hardcoding this can actually reduce flexibility in Morpho's pausing discretion since one action on Morpho can actually constitute multiple types of interactions with the pool.
3. Some of the checks are gas intensive as information from the pool needs to be fetched.

**Comment by MathisGD** [comment]
Thanks !

(1.) notably makes a lot of sense
